# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('crit', models.IntegerField()),
                ('time', models.IntegerField()),
                ('label', models.TextField(default='')),
                ('status', models.CharField(choices=[('U', 'Unlabeled'), ('I', 'Labeling'), ('L', 'Labeled'), ('A', 'Abandoned')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LabelId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crit', models.IntegerField()),
                ('label_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('passwd', models.CharField(max_length=128)),
                ('num_labeled', models.IntegerField(default=0)),
                ('labeling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labeled_data.Data')),
            ],
        ),
    ]
