# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeled_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='label',
        ),
        migrations.RemoveField(
            model_name='data',
            name='status',
        ),
        migrations.AddField(
            model_name='data',
            name='num_labeled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='num_labeling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_crit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='label',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labeled_data.User'),
        ),
        migrations.AddField(
            model_name='label',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeled_data.Data'),
        ),
    ]
